#!/usr/bin/env python3
"""
fonts/regenerate.py — このサイトのセルフホスト Web フォント資産を再生成する。

生成物:
  public/fonts/barlow-condensed/*.woff2   … Barlow Condensed 8 ウェイト（フルセット）
  public/fonts/noto-sans-jp/*.woff2       … Noto Sans JP 124 チャンク（unicode-range 分割・可変フォント）
  public/css/fonts.css                    … 上記を束ねる @font-face 定義（手で編集しない）

前提:
  - グローバルスキル webfont-selfhost が ~/.claude/skills/webfont-selfhost に入っていること
  - fontTools + brotli (pip install fonttools brotli)
  - ソースフォントが fonts/src/ にあること（BarlowCondensed-*.ttf, NotoSansJP[wght].ttf）
  - unicode-range の定義元 fonts/noto-sans-jp.google.css があること
    （Google css2 の出力。再取得するなら下記コメントの curl を使う）

使い方（リポジトリ直下から）:
  python3 fonts/regenerate.py

# unicode-range 定義元（fonts/noto-sans-jp.google.css）の再取得が必要なとき:
#   curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 \
#     (KHTML, like Gecko) Chrome/120.0 Safari/537.36" \
#     "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700;900&display=swap" \
#     -o fonts/noto-sans-jp.google.css
#   ※ 近代的な User-Agent でないと Google は unicode-range 付き woff2 CSS を返さない
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKILL = os.path.expanduser("~/.claude/skills/webfont-selfhost/scripts")
SRC = os.path.join(ROOT, "fonts", "src")
RANGES_CSS = os.path.join(ROOT, "fonts", "noto-sans-jp.google.css")
PUB_FONTS = os.path.join(ROOT, "public", "fonts")
FONTS_CSS = os.path.join(ROOT, "public", "css", "fonts.css")

# Barlow Condensed: font-weight -> ソースファイル名サフィックス
BARLOW = [
    (100, "Thin"), (200, "ExtraLight"), (400, "Regular"), (500, "Medium"),
    (600, "SemiBold"), (700, "Bold"), (800, "ExtraBold"), (900, "Black"),
]


def need(path, what):
    if not os.path.exists(path):
        sys.exit(f"ERROR: {what} が見つかりません: {path}")


def run(cmd):
    print("  $", " ".join(os.path.basename(c) if c.endswith(".py") else c for c in cmd))
    subprocess.run(cmd, check=True)


def main():
    need(os.path.join(SKILL, "to_woff2.py"), "webfont-selfhost スキル")
    need(RANGES_CSS, "Google CSS（unicode-range 定義元）")
    need(os.path.join(SRC, "NotoSansJP[wght].ttf"), "Noto Sans JP ソース")

    # 1) Barlow Condensed 8 ウェイト -> woff2
    print("[1/3] Barlow Condensed -> woff2")
    barlow_inputs = [os.path.join(SRC, f"BarlowCondensed-{name}.ttf") for _, name in BARLOW]
    run([sys.executable, os.path.join(SKILL, "to_woff2.py"), *barlow_inputs,
         "--out", os.path.join(PUB_FONTS, "barlow-condensed")])

    # 2) Noto Sans JP -> unicode-range 分割 woff2 + 部分 CSS
    print("[2/3] Noto Sans JP -> unicode-range チャンク")
    noto_css = os.path.join(ROOT, "fonts", "_noto.generated.css")
    run([sys.executable, os.path.join(SKILL, "chunk_cjk.py"),
         "--font", os.path.join(SRC, "NotoSansJP[wght].ttf"),
         "--ranges-from", RANGES_CSS,
         "--family", "Noto Sans JP",
         "--weight-range", "100 900",
         "--name-prefix", "notosansjp",
         "--out-dir", os.path.join(PUB_FONTS, "noto-sans-jp"),
         "--url-prefix", "../fonts/noto-sans-jp",
         "--css-out", noto_css,
         "--display", "swap"])

    # 3) public/css/fonts.css を組み立て（Barlow ブロック + Noto ブロック）
    print("[3/3] public/css/fonts.css を組み立て")
    barlow_blocks = []
    for w, name in BARLOW:
        barlow_blocks.append(
            "@font-face {\n"
            "  font-family: 'Barlow Condensed';\n"
            "  font-style: normal;\n"
            f"  font-weight: {w};\n"
            "  font-display: swap;\n"
            f"  src: url('../fonts/barlow-condensed/BarlowCondensed-{name}.woff2') format('woff2');\n"
            "}\n"
        )
    barlow_css = ("/* Barlow Condensed — self-hosted (full latin, 8 weights). "
                  "Generated by webfont-selfhost. Do not hand-edit. */\n"
                  + "\n".join(barlow_blocks))

    header = (
        "/*! ============================================================\n"
        " *  fonts.css — セルフホスト Web フォント定義（自動生成）\n"
        " *  生成: fonts/regenerate.py + ~/.claude/skills/webfont-selfhost\n"
        " *  - Barlow Condensed: フルセット 8 ウェイト\n"
        " *  - Noto Sans JP: unicode-range 分割（124チャンク・可変フォント）\n"
        " *  手で編集しないこと。再生成は `python3 fonts/regenerate.py`。\n"
        " * ============================================================ */\n\n"
    )

    with open(noto_css, encoding="utf-8") as f:
        noto_blocks = f.read()
    with open(FONTS_CSS, "w", encoding="utf-8") as f:
        f.write(header + barlow_css + "\n" + noto_blocks)
    os.remove(noto_css)  # 中間ファイルは残さない

    n_noto = len([n for n in os.listdir(os.path.join(PUB_FONTS, "noto-sans-jp"))
                  if n.endswith(".woff2")])
    print(f"完了: public/css/fonts.css（Barlow 8 + Noto {n_noto} = "
          f"{8 + n_noto} @font-face）")


if __name__ == "__main__":
    main()
